version: "3.8"

services:
  db:
    build:
      context: ./docker
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "8432:8432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
